"""Rendering of the data-driven AWM/HASP paper figures.

Only the two quantitative paper figures are reproduced here; the hand-drawn
architecture figure and the qualitative entity-grounding visualisations are
shipped as finished PDFs and are not regenerated by this package.
"""
