#!/usr/bin/env python3
"""Export formal CLEVRER predictive-QA latent chunks for one scene.

The exported observed chunk corresponds to raw frames 96,100,...,124 and the
future chunk is generated by the frozen V-JEPA2 predictor (128,132,...,156).
No future RGB frames are read by the model.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path

import numpy as np
import torch
import yaml
from decord import VideoReader, cpu
from torch.utils.data import DataLoader, Dataset
from src.training.distributed import ExactDistributedSampler

from src.data.clevrer.export_qa_trajectories import FullFrameResize
from src.core.world_model_loader import load_configured_model
from src.core.config_utils import merged_task_experiment
from src.core.run_context import apply_cli_defaults, task_context


# Canonical AWM CLEVRER config: it carries the shared ``tasks.train.experiment``
# world-model block that ``merged_task_experiment(..., "qa_eval")`` reads.
DEFAULT_CONFIG = Path("configs/clevrer/awm_clevrer_fullpatch_probe_seed239/config.yaml")
DEFAULT_CHECKPOINT = Path(
    "/data/shyang/outputs/vjepa2-baiz/vjepa2_naive/"
    "clevrer_vith_16to16_stride2_8gpu/best.pt"
)
DEFAULT_VIDEO_ROOT = Path("/data/shared/datasets/CLEVRER/videos")
DEFAULT_OUTPUT_ROOT = Path(
    "/data/shyang/outputs/vjepa2-baiz/reproduce_v1_clevrer_only/"
    "clevrer_predictive_latents_v1"
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_config(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        return merged_task_experiment(yaml.safe_load(handle), "qa_eval")


def load_scene(video_path: Path, crop_size: int) -> torch.Tensor:
    reader = VideoReader(str(video_path), num_threads=-1, ctx=cpu(0))
    if len(reader) != 128:
        raise ValueError(f"formal CLEVRER QA requires 128 raw frames, got {len(reader)}: {video_path}")
    indices = np.arange(0, 128, 2, dtype=np.int64)
    frames = reader.get_batch(indices).asnumpy()
    video = FullFrameResize(crop_size)(frames)
    if tuple(video.shape) != (3, 64, crop_size, crop_size):
        raise ValueError(f"unexpected transformed video shape: {tuple(video.shape)}")
    return video


class VideoDataset(Dataset):
    def __init__(self, root: Path, split: str, crop_size: int, scene_id: int | None = None):
        self.split = split
        self.crop_size = crop_size
        directory = root / {"validation": "val", "train": "train", "test": "test"}[split]
        self.samples = sorted(directory.glob("video_*.mp4"))
        if scene_id is not None:
            self.samples = [p for p in self.samples if p.stem == f"video_{scene_id:05d}"]
        if not self.samples:
            raise FileNotFoundError(f"no CLEVRER videos under {directory}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, index):
        path = self.samples[index]
        scene_id = int(path.stem.split("_")[-1])
        return scene_id, load_scene(path, self.crop_size)


def init_distributed():
    if "RANK" not in os.environ:
        return 0, 1, 0
    rank = int(os.environ["RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    if torch.cuda.is_available():
        torch.cuda.set_device(local_rank)
        torch.distributed.init_process_group("nccl", init_method="env://")
    return rank, world_size, local_rank


@torch.inference_mode()
def export(args):
    rank, world_size, local_rank = init_distributed()
    if world_size > 1:
        device = torch.device(f"cuda:{local_rank}")
    else:
        device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    config = load_config(args.config)
    data_cfg = config.get("data", {})
    checkpoint = args.checkpoint
    if not checkpoint.is_file():
        raise FileNotFoundError(f"world-model checkpoint does not exist: {checkpoint}")

    model, model_metadata = load_configured_model(config, checkpoint, device)
    model.eval()
    clip_frames = int(model.clip_frames)
    if clip_frames != 16 or int(model.temporal_steps) != 8:
        raise ValueError(
            f"formal predictive export expects clip_frames=16 and temporal_steps=8, "
            f"got {clip_frames} and {model.temporal_steps}"
        )
    crop_size = int(getattr(model, "crop_size", data_cfg.get("crop_size", 256)))
    splits = ["train", "validation", "test"] if args.split == "all" else [args.split]
    for split in splits:
        dataset = VideoDataset(args.video_root, split, crop_size, args.scene_id)
        sampler = ExactDistributedSampler(dataset, rank=rank, world_size=world_size)
        loader = DataLoader(dataset, sampler=sampler, batch_size=args.batch_size,
                            num_workers=args.num_workers, pin_memory=True)
        output_dir = args.output_root / split
        if rank == 0:
            output_dir.mkdir(parents=True, exist_ok=True)
        if world_size > 1:
            torch.distributed.barrier()
        for scene_ids, videos in loader:
            videos = videos.to(device, non_blocking=True)
            current = model.encode_current(videos[:, :, -clip_frames:])
            future = model.predict_next(current)
            observed = current.reshape(videos.size(0), model.temporal_steps, model.spatial_tokens, -1).float().cpu()
            imagined = future.reshape(videos.size(0), model.temporal_steps, model.spatial_tokens, -1).float().cpu()
            for row, scene_id in enumerate(scene_ids.tolist()):
                output = args.output_root / split / f"scene_{scene_id:05d}.pt"
                if output.is_file() and args.resume:
                    continue
                record = {
                    "protocol_version": "clevrer_predictive_latents_v1",
                    "scene_index": int(scene_id),
                    "observed_tokens": observed[row],
                    "future_tokens": imagined[row],
                    "visual_tokens": torch.cat((observed[row], imagined[row]), dim=0),
                    "observed_raw_frame_times": [96, 100, 104, 108, 112, 116, 120, 124],
                    "imagined_raw_frame_times": [128, 132, 136, 140, 144, 148, 152, 156],
                    "imagined_reads_future_rgb": False,
                    "video": str((args.video_root / {"validation": "val", "train": "train", "test": "test"}[split] / f"video_{scene_id:05d}.mp4").resolve()),
                    "split": split,
                    "world_model_checkpoint": str(checkpoint.resolve()),
                    "world_model_checkpoint_sha256": sha256(checkpoint),
                    "world_model_metadata": model_metadata,
                    "config": str(args.config.resolve()),
                }
                output.parent.mkdir(parents=True, exist_ok=True)
                torch.save(record, output)
        if world_size > 1:
            torch.distributed.barrier()
    if rank == 0:
        print(json.dumps({"output_root": str(args.output_root.resolve()), "splits": splits}, indent=2))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scene-id", type=int, default=None, help="兼容单 scene 导出；批量模式请省略")
    parser.add_argument("--split", choices=("train", "validation", "test", "all"), default="all")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    parser.add_argument("--video-root", type=Path, default=DEFAULT_VIDEO_ROOT)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--resume", action="store_true")
    apply_cli_defaults(parser, task_context())
    export(parser.parse_args())


if __name__ == "__main__":
    main()
