#!/usr/bin/env python3
"""Run the frozen structured CLEVRER QA model on one random predictive question.

The input follows the formal QA protocol: one exported scene trajectory with
8 observed latent steps (raw frames 96..124, stride 4) followed by 8 imagined
steps (raw frames 128..156, generated by the predictor).  The full-patch
``window_start`` cache is intentionally not accepted here because it is a
different data protocol.
"""
from __future__ import annotations

import argparse
import json
import random
import shutil
from pathlib import Path

import torch

from src.experiments.awm_clevrer_fullpatch_probe_seed239.model import CLEVRERDecoder
from src.data.clevrer.qa_dataset import WordTokenizer
from src.data.clevrer.qa_model import build_qa_model


DEFAULT_ANNOTATIONS = Path("/data/shared/datasets/CLEVRER/official_code/executor/data")
DEFAULT_TRAJECTORY_ROOT = Path(
    "/data/shyang/outputs/vjepa2-baiz/reproduce_v1_clevrer_only/"
    "clevrer_predictive_latents_v1"
)
DEFAULT_QA_CHECKPOINT = Path(
    "outputs/runs/reproduce_v1_clevrer_only/"
    "vjepa2_naive_probe_v5_decoder/"
    "clevrer_vith_16to16_dynamics_decoder_v1_8gpu/evaluations/"
    "qa_dynamics_decoder_v1/qa_checkpoints/current_future/best.pt"
)
DEFAULT_PROBE_CHECKPOINT = Path(
    "outputs/runs/reproduce_v1_clevrer_only/"
    "vjepa2_naive_probe_v5_decoder/"
    "clevrer_dynamics_decoder_multiwindow_seed239_retry_v1/best.pt"
)
DEFAULT_VIDEO_ROOT = Path("/data/shared/datasets/CLEVRER/videos/val")
DEFAULT_OUTPUT_ROOT = Path(
    "outputs/runs/reproduce_v1_clevrer_only/"
    "clevrer_analyseIntervention/random_predictive_qa"
)


def _load_json(path: Path):
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def load_probe(checkpoint: Path, device: torch.device):
    payload = torch.load(checkpoint, map_location="cpu", weights_only=False)
    if payload.get("protocol") != "clevrer_fullpatch_dynamics_decoder_v1":
        raise ValueError(f"unexpected structured probe protocol: {payload.get('protocol')!r}")
    model = CLEVRERDecoder(**payload["model_config"]).to(device)
    model.load_state_dict(payload["model"], strict=True)
    model.eval()
    return model, payload


def choose_question(
    annotation_root: Path,
    trajectory_root: Path,
    video_root: Path,
    seed: int,
    scene_id: int | None = None,
):
    scenes = _load_json(annotation_root / "validation.json")
    questions = [
        (scene, question)
        for scene in scenes
        if scene_id is None or int(scene["scene_index"]) == int(scene_id)
        for question in scene["questions"]
        if question["question_type"] == "predictive"
        and (trajectory_root / "validation" / f"scene_{int(scene['scene_index']):05d}.pt").is_file()
        and (video_root / f"video_{int(scene['scene_index']):05d}.mp4").is_file()
    ]
    if not questions:
        raise ValueError("no predictive question found in the requested validation scenes")
    return random.Random(seed).choice(questions)


def _qa_batch(question, tokenizer, video_emb, probe_outputs):
    choices = question.get("choices", [])
    if not choices:
        raise ValueError("predictive question has no choices")
    q_tokens = torch.stack(
        [tokenizer.encode_mc(question["question"], choice["choice"]) for choice in choices]
    )
    return {
        "mc_video_emb": video_emb.unsqueeze(0),
        "mc_q_tokens": q_tokens,
        "mc_flag": torch.zeros(len(choices), dtype=torch.long),
        "mc_probe_outputs": {
            name: value.unsqueeze(0) for name, value in probe_outputs.items()
        },
        "mc_label": torch.tensor(
            [int(choice.get("answer") == "correct") for choice in choices], dtype=torch.long
        ),
        "mc_choice_id": torch.tensor(
            [int(choice["choice_id"]) for choice in choices], dtype=torch.long
        ),
        "mc_meta": [
            {
                "scene_index": int(question["_scene_index"]),
                "question_id": int(question["question_id"]),
                "question_type": "predictive",
            }
        ],
        "mc_subtype": torch.tensor([2], dtype=torch.long),
        "mc_flag": torch.zeros(len(choices), dtype=torch.long),
        "cls_q_tokens": torch.empty(0, 0, dtype=torch.long),
        "cls_video_emb": torch.empty(0, *video_emb.shape),
        "cls_label": torch.empty(0, dtype=torch.long),
        "cls_probe_outputs": None,
    }


def run(args):
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    question_scene, question = choose_question(
        args.annotations,
        args.trajectory_root,
        args.video_root,
        args.seed,
        args.scene_id,
    )
    scene_index = int(question_scene["scene_index"])
    question = dict(question)
    question["_scene_index"] = scene_index
    trajectory_path = args.trajectory_root / "validation" / f"scene_{scene_index:05d}.pt"
    if not trajectory_path.is_file():
        raise FileNotFoundError(
            f"formal QA trajectory does not exist: {trajectory_path}. "
            "Run export_qa_trajectories with the QA config first; do not use "
            "the full-patch window cache."
        )
    video_path = args.video_root / f"video_{scene_index:05d}.mp4"
    if not video_path.is_file():
        raise FileNotFoundError(f"CLEVRER validation video does not exist: {video_path}")

    qa_payload = torch.load(args.qa_checkpoint, map_location="cpu", weights_only=False)
    if qa_payload.get("protocol") != "clevrer_v2_learned16_structured_supervised_sequence_probes_native_aloe_qa_v1":
        raise ValueError(f"unexpected QA checkpoint protocol: {qa_payload.get('protocol')!r}")
    tokenizer = WordTokenizer.from_state_dict(qa_payload["tokenizer"])
    qa_model = build_qa_model(
        qa_payload["qa_config"], qa_payload["visual_dim"], tokenizer,
        qa_payload["answer_vocabulary"],
    ).to(device)
    qa_model.load_state_dict(qa_payload["model"], strict=True)
    qa_model.eval()

    record = torch.load(trajectory_path, map_location="cpu", weights_only=True)
    video_emb = record["visual_tokens"].float()
    if tuple(video_emb.shape[:2]) != (16, 256):
        raise ValueError(f"formal QA trajectory visual_tokens must be [16,256,D], got {tuple(video_emb.shape)}")
    saved_probe = record.get("probe_outputs")
    if saved_probe is not None:
        probe_outputs = {name: value.float() for name, value in saved_probe.items()}
        probe_payload = record.get("probe_metadata", {})
    else:
        probe, probe_payload = load_probe(args.probe_checkpoint, device)
        with torch.inference_mode():
            raw = probe(video_emb[:8].to(device).unsqueeze(0), video_emb[8:].to(device).unsqueeze(0))
            valid = raw["presence_logits"].sigmoid().ge(0.5)
            sparse = valid.sum(dim=1).lt(2)
            if sparse.any():
                top = raw["presence_logits"][sparse].topk(k=2, dim=1).indices
                valid[sparse] = False
                valid[sparse[:, None], top] = True
            first, second = probe.probes.pair_indices[:, 0], probe.probes.pair_indices[:, 1]
            probe_outputs = {
                "object_tokens": raw["object_tokens"][0].float().cpu(),
                "pair_tokens": raw["pair_tokens"][0].float().cpu(),
                "object_valid": valid[0].cpu(),
                "pair_valid": (valid[:, first] & valid[:, second])[0].cpu(),
                **{name: raw[name][0].float().cpu() for name in (
                    "presence_logits", "color_logits", "material_logits", "shape_logits",
                    "trajectory_2d", "pair_distance_2d", "contact_gt_event", "first_contact_logits",
                )},
            }
    with torch.inference_mode():
        batch = _qa_batch(question, tokenizer, video_emb.cpu(), probe_outputs)
        batch = {
            key: (value.to(device) if torch.is_tensor(value) else value)
            for key, value in batch.items()
        }
        batch["mc_probe_outputs"] = {
            name: value.to(device) for name, value in batch["mc_probe_outputs"].items()
        }
        logits = qa_model(batch)["mc_answer_logits"].float().cpu()
    probabilities = logits.sigmoid().tolist()
    predicted_index = int(logits.argmax().item())
    choices = []
    for index, (choice, probability) in enumerate(zip(question["choices"], probabilities)):
        choices.append({
            "choice_id": int(choice["choice_id"]),
            "choice": choice["choice"],
            "ground_truth": choice.get("answer"),
            "probability": float(probability),
            "predicted": index == predicted_index,
        })
    correct_indices = [
        index for index, choice in enumerate(question["choices"])
        if choice.get("answer") == "correct"
    ]
    is_correct = predicted_index in correct_indices
    predicted_choice = question["choices"][predicted_index]
    correct_choices = [question["choices"][index] for index in correct_indices]
    ranked_indices = sorted(range(len(probabilities)), key=lambda index: probabilities[index], reverse=True)
    for rank, index in enumerate(ranked_indices, start=1):
        choices[index]["rank"] = rank
    result = {
        "protocol": "clevrer_random_predictive_qa_v1",
        "seed": int(args.seed),
        "scene_index": scene_index,
        "question_id": int(question["question_id"]),
        "question_type": "predictive",
        "question": question["question"],
        "choices": choices,
        "predicted_answer": choices[predicted_index]["choice"],
        "ground_truth_answer": [c["choice"] for c in choices if c.get("ground_truth") == "correct"],
        "predicted_choice_id": int(predicted_choice["choice_id"]),
        "correct_choice_ids": [int(choice["choice_id"]) for choice in correct_choices],
        "is_correct": bool(is_correct),
        "correctness": {
            "status": "correct" if is_correct else "incorrect",
            "explanation": (
                "模型预测的选项与标注的 correct 选项一致。"
                if is_correct else
                "模型预测的选项与标注的 correct 选项不一致。"
            ),
        },
        "video": str(video_path.resolve()),
        "trajectory": str(trajectory_path.resolve()),
        "observed_raw_frame_times": [96, 100, 104, 108, 112, 116, 120, 124],
        "imagined_raw_frame_times": [128, 132, 136, 140, 144, 148, 152, 156],
        "qa_checkpoint": str(args.qa_checkpoint.resolve()),
        "probe_checkpoint": probe_payload.get("checkpoint", str(args.probe_checkpoint.resolve())),
        "world_protocol": str(record.get("protocol", "")),
        "probe_epoch": int(probe_payload.get("checkpoint_epoch", -1)),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    video_output = args.output.parent / video_path.name
    shutil.copy2(video_path, video_output)
    result["video_output"] = str(video_output.resolve())
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--annotations", type=Path, default=DEFAULT_ANNOTATIONS)
    parser.add_argument("--trajectory-root", type=Path, default=DEFAULT_TRAJECTORY_ROOT)
    parser.add_argument("--qa-checkpoint", type=Path, default=DEFAULT_QA_CHECKPOINT)
    parser.add_argument("--probe-checkpoint", type=Path, default=DEFAULT_PROBE_CHECKPOINT)
    parser.add_argument("--video-root", type=Path, default=DEFAULT_VIDEO_ROOT)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--seed", type=int, default=239)
    parser.add_argument("--scene-id", type=int, default=None)
    parser.add_argument("--device", default="cuda:0")
    args = parser.parse_args()
    if args.output is None:
        args.output = args.output_root / f"seed_{args.seed:03d}" / "random_predictive_qa.json"
    run(args)


if __name__ == "__main__":
    main()
